Add flash message for user
PetroFedun/blog pull request #10
Opened 2023-03-23 18:42 UTC by PetroFedun

2023-03-23 21:11 UTC, MishaIlchyshyn requested changes

2023-03-23 21:11 UTC, MishaIlchyshyn commented on app/views/devise/shared/_error_messages.html.erb
> +        <li ><%= message %></li>
не так `<li > `
так `<li>`

2023-03-23 21:11 UTC, MishaIlchyshyn commented on config/routes.rb
> +
це шо?

2023-03-23 21:11 UTC, MishaIlchyshyn commented on db/migrate/20230321193620_create_active_storage_tables.active_storage.rb
> +class CreateActiveStorageTables < ActiveRecord::Migration[5.2]
помоєму це в тебе вже було в якомусь ПР ?

2023-03-23 21:11 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +.alert-alert {
якась назва як на мене не понятна (.alert-alert)
дублювання якесь

2023-03-23 21:11 UTC, MishaIlchyshyn commented on app/controllers/articles_controller.rb
> +      flash[:success] = "Article update!"
різниця в тому що закінчення ed означає минулий час
update - оновити
updated - оновлено

2023-03-23 21:11 UTC, MishaIlchyshyn commented on app/controllers/application_controller.rb
> +  include ErrorHandling
виглядає нібм ти це не використовуєш
попробуй видалити і перевір чи всьо працює
якщо так то видаляй цю штуку взагалі і сам клас тоже

2023-03-23 21:11 UTC, MishaIlchyshyn commented on app/controllers/concerns/error_handling.rb
> +module ErrorHandling
про цю штуку написав вище

2023-03-23 21:15 UTC, MishaIlchyshyn commented
@PetroFedun зверни увагу на назву гілки **adding-messages-for-user** не відображає суті
так вроді краще flash-messages
цю гілку вже не переназивай

І назва ПР - Add flash message**s** for user

2023-03-24 10:13 UTC, PetroFedun commented on app/models/comment.rb
> +  validates :commenter, presence: true, length: { minimum: 2 }
наприклад
Commenter: Misha Ilchyshyn
Comment: Some text

2023-03-24 10:16 UTC, PetroFedun commented on app/controllers/application_controller.rb
> +  include ErrorHandling
це штука працює так що коли юзер пробує найти статю по айді якої не існує воно його перенаправляє на сторінку з помилкою "The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved."

2023-03-24 10:17 UTC, PetroFedun commented on db/migrate/20230321193620_create_active_storage_tables.active_storage.rb
> +class CreateActiveStorageTables < ActiveRecord::Migration[5.2]
можливо, просто я скидав базу даних і нанової її заповняв в цій цілці

2023-03-24 10:30 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +.alert-alert {
ок

2023-03-24 11:03 UTC, PetroFedun commented on config/routes.rb
> +
🤷🏻‍♂️

2023-03-27 18:00 UTC, MishaIlchyshyn commented on config/routes.rb
> +
видали цей відступ і можеш мерджити в меін

2023-03-27 19:18 UTC, merged