add archiving/unarchiving posts
PetroFedun/blog pull request #13
Opened 2023-04-15 19:08 UTC by PetroFedun

2023-04-18 20:47 UTC, MishaIlchyshyn requested changes

2023-04-18 20:47 UTC, MishaIlchyshyn commented on app/controllers/articles_controller.rb
> +    end
а ще цю умову можна записати в одну лінійку
**@articles = current_user ? current_user.articles.kept : Article.kept**

2023-04-18 20:47 UTC, MishaIlchyshyn commented on app/views/articles/arhived.html.erb
> +    <% @articles.each do |article| %>
@archived_articles

2023-04-18 20:47 UTC, MishaIlchyshyn commented on app/views/articles/arhived.html.erb
> +          <img src="<%= asset_path('panda.jpg') %>" class="card-img-top" alt="..." style="padding-top: 12px;">
думаю що погана ідея ставити панду якщо не вибрана фотка.
підбери щось нейтральне щоб було понятно що воно підставилось по дефолту

2023-04-18 20:47 UTC, MishaIlchyshyn commented on app/views/articles/arhived.html.erb
> +      <div class="card-body">
фотка має бути частиною card-body

2023-04-18 20:47 UTC, MishaIlchyshyn commented on app/views/articles/show.html.erb
> +  <% end %>
неправильні відступи

2023-04-18 20:47 UTC, MishaIlchyshyn commented on app/views/articles/show.html.erb
> +    <% if can? :destroy, @article %>
не певнений що це правильно
чому :destroy ?

2023-04-18 20:47 UTC, MishaIlchyshyn commented on app/views/articles/show.html.erb
> +                                data: {
виглядає ніби тут не треба data

2023-04-18 20:47 UTC, MishaIlchyshyn commented on app/views/articles/show.html.erb
> +                                data: {
і тут data напевне лишня

2023-04-18 20:47 UTC, MishaIlchyshyn commented on app/views/layouts/_header.html.erb
> +            <li><%= link_to "Arhived", article_arhived_path, class: "btn btn-primary btn-dropdown" %></li>
Arhived articles

2023-04-19 11:25 UTC, MishaIlchyshyn commented on app/views/articles/arhived.html.erb
> +      <div class="card-body">
а нє, тут я помилився, всьо ок

2023-04-21 10:02 UTC, MishaIlchyshyn commented on app/controllers/articles_controller.rb
> +  before_action :authenticate_user!, only: %i[create new]
цього тут немає бути

2023-04-21 11:25 UTC, PetroFedun commented on app/controllers/articles_controller.rb
> +  before_action :authenticate_user!, only: %i[create new]
чого?

2023-04-21 13:22 UTC, MishaIlchyshyn commented on app/controllers/articles_controller.rb
> +  before_action :authenticate_user!, only: %i[create new]
що робить метод `authenticate_user!`?

2023-04-21 17:06 UTC, PetroFedun commented on app/controllers/articles_controller.rb
> +  before_action :authenticate_user!, only: %i[create new]
надає право створювати пости тілька аутентифікованим юзерам

2023-04-24 10:14 UTC, MishaIlchyshyn requested changes

2023-04-24 10:14 UTC, MishaIlchyshyn commented on app/controllers/articles_controller.rb
> +  before_action :authenticate_user!, only: %i[create new]
а що на рахунок редагування і видалення?
ці дії можуть робити також тільки залогінені користувачі

2023-04-24 10:14 UTC, MishaIlchyshyn commented on app/controllers/articles_controller.rb
> -    authorize! :create, @article
а що робила ця штука?
і чого ти її видалив?

2023-04-24 11:29 UTC, PetroFedun commented on app/controllers/articles_controller.rb
> -    authorize! :create, @article
ну по ідеї то саме але відколи я додав канкан то вона вже не потрібна стала

2023-04-24 11:32 UTC, PetroFedun commented on app/controllers/articles_controller.rb
> -    authorize! :create, @article
хоча я думаю цю штуку authenticate_user! додати в метод create просто і буде то саме

2023-04-24 11:59 UTC, MishaIlchyshyn commented on app/controllers/articles_controller.rb
> -    authorize! :create, @article
authorize! :create, @article так це і є хелпер cancan
https://github.com/CanCanCommunity/cancancan/blob/develop/docs/controller_helpers.md#controller-helpers

2023-04-24 12:10 UTC, MishaIlchyshyn commented on app/controllers/articles_controller.rb
> -    authorize! :create, @article
треба прочитати цю [доку](https://github.com/CanCanCommunity/cancancan/tree/develop/docs) і зрозуміти як працює cancan
бо я не дуже розумію але здається що cancan мав би керувати тим чи може певний юзер щось робити на сторінці чи не може (створювати, редагувати і тд.)

2023-04-24 17:00 UTC, merged