Move 'New article' and 'Archived articles'
PetroFedun/blog pull request #14
Opened 2023-04-25 14:24 UTC by PetroFedun

2023-04-25 18:28 UTC, MishaIlchyshyn requested changes

2023-04-25 18:28 UTC, MishaIlchyshyn commented on app/views/articles/index.html.erb
підправ сітку

![image](https://user-images.githubusercontent.com/28114539/234364092-067d7f39-7946-400d-bee7-93c3271cae48.png)

2023-04-25 18:28 UTC, MishaIlchyshyn commented on app/views/articles/index.html.erb
> +  <h1 class="title" style="margin-top: -3rem;">Articles</h1>
title вверху, меню під ним

2023-04-27 12:42 UTC, MishaIlchyshyn requested changes

2023-04-27 12:42 UTC, MishaIlchyshyn commented on app/views/articles/archived_articles.html.erb
> +            <img src="<%= asset_path('default-article-img.jpg') %>" class="card-img-top" alt="..." style="padding-top: 12px;">
чому в тебе в одному випадку картинка в блоці text-center а в іншому без нього?
попробуй винести text-center на верхній рівень
типу:
```
<%= link_to article do %>
  <div class="text-center">
    <% if article.preview_img.present? %>
      <%= image_tag article.preview_img, class:"article-preview-img" %>
    <% else %>
      <img src="<%= asset_path('default-article-img.jpg') %>" class="article-preview-img">
```
і так як картинки в тебе відображаються однаково то і стилі по ідеї мають бути однакові, тому попробуй винести стилі для цієї картинки в окремий клас `article-preview-img` і використати в двох випадках

ці зміни трохи мали б зробити код читабельнішим

2023-04-27 12:42 UTC, MishaIlchyshyn commented on app/views/articles/archived_articles.html.erb
> +    <h2 class="mb-4">There is no arhived article yet</h2>
`<div class="p-5 m-5 text-center bg-primary bg-gradient text-white">` - цей блок помоєму лишній
зверни увагу що коли сторінка пуста то футер прилягає до хедера
попробуй прижати футер до низу сторінки навіть при пустій сторінці
і потім на цій сторінці лиши текст **There is no arhived articles yet** по центру сторінки (горизонтально / вертикально)

2023-04-27 12:42 UTC, MishaIlchyshyn commented on app/views/articles/index.html.erb
> +
?

2023-04-27 12:42 UTC, MishaIlchyshyn commented on app/views/articles/index.html.erb
> +  <div class="row mx-auto" id="card-flex">
ще один момент
сторінка archived_articles і index відображають однаковий список постів
<% if @archived_articles.present? %>
<% if @articles.present? %>

тобі треба зробити паршал наприклад _articles і винести в нього список постів і передавати в нього @archived_articles або @articles

2023-04-27 14:23 UTC, MishaIlchyshyn commented
@PetroFedun додай в назву ПРа позначку WIP (work in progress)
Move 'New article' and 'Archived articles' [WIP]

і видалиш коли доробиш всі зміни

2023-04-27 21:00 UTC, MishaIlchyshyn requested changes

2023-04-27 21:00 UTC, MishaIlchyshyn commented on app/views/articles/_article.html.erb
> +        <div class="text-center">
дивно що в тебе клас з назвою text-center в даному випадку немає ніякого відношення до тексту.
попробуй взагалі забрати цей клас

2023-04-27 21:00 UTC, MishaIlchyshyn commented on app/views/articles/_article.html.erb
> +            <img src="<%= asset_path('default-article-img.jpg') %>" class="card-img-top" alt="..." style="padding-top: 12px;">
ти пропустив комент де я писав про стилі для img
видали style в двох випадках
всі стилі для цього мають бути в одному класі class="card-img-top"
ще ліпше переназви клас  на -> article-preview-img
має вийти шось таке:
```
<% if article.preview_img.present? %>
      <%= image_tag article.preview_img, class:"article-preview-img" %>
    <% else %>
      <img src="<%= asset_path('default-article-img.jpg') %>" class="article-preview-img">
```

2023-04-28 07:51 UTC, PetroFedun commented on app/views/layouts/application.html.erb
> +      <div class="pb-5">
футер просто чуть залазить на вміст сторінки

2023-04-28 08:11 UTC, MishaIlchyshyn commented on app/views/layouts/application.html.erb
> +      <div class="pb-5">
значить походу сітка не правильно побудована
переглянь сітку і попробуй якось без цих костилів зробити
трохи побався, якщо не зможеш то лишай як є

2023-04-28 13:15 UTC, MishaIlchyshyn requested changes

2023-04-28 13:15 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +  color: $white;
а для чого ти поміняв порядок?

2023-04-28 13:15 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +    padding-right: 20px;
а ти точно тут не хотів зробити **padding: auto 20px** ?

2023-04-28 13:15 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +.form-width {
```
#feedbackform {
  width: 75%;
}
```
думаю не варто плодити такі класи і айдішки
просто в формі задати width через бутстрапівський клас (думаю такий є)

2023-04-28 13:15 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +  .form-width {
по назві класу ти думаєш що він задає ширину для форми, а він виявляється ще й додає рамки і падінги

2023-04-28 13:15 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +    margin: 15px 0;
відступи

2023-04-28 13:15 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +  .right-margin {
безполєзний клас

2023-04-28 13:15 UTC, MishaIlchyshyn commented on app/views/layouts/application.html.erb
> +      <%= render 'layouts/footer'%>
<%= yield %> - це по ідеї і є main який ти додаєш на каожній сторінці
треба стилізувати тут 
```
<div class='...'>
  <%= yield %>
</div>
```

2023-04-28 13:15 UTC, MishaIlchyshyn commented on app/views/articles/archived_articles.html.erb
> +<main>
не треба на кожну сторінку додавати main

2023-04-28 13:43 UTC, PetroFedun commented on app/assets/stylesheets/style.scss
> +$gray: gray;
опше в зміних з кольорами?

2023-04-28 13:43 UTC, PetroFedun commented on app/assets/stylesheets/style.scss
> +$gray: gray;
ну смисл в тім що $white лекше запамятати і потім десь заюзати ніж #fff

2023-04-28 13:44 UTC, PetroFedun commented on app/assets/stylesheets/style.scss
> +  color: $white;
ну так правильніше

2023-04-28 13:45 UTC, PetroFedun commented on app/assets/stylesheets/style.scss
> +    padding-right: 20px;
ну мені ауто зверху не потрібно як виявилося

2023-04-28 13:46 UTC, PetroFedun commented on app/assets/stylesheets/style.scss
> +.form-width {
також так думаю але це потрібно щоб при адаптиві форма займала 100% а класами бутсрап такого чогось не можу добитися

2023-04-28 13:49 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +$gray: gray;
$gray: gray;

2023-04-28 13:50 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +  color: $white;
чим?

2023-04-28 13:51 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +    padding-right: 20px;
ок

2023-04-28 14:03 UTC, PetroFedun commented on app/assets/stylesheets/style.scss
> +$gray: gray;
ну це вже щоб один стиль написання кольорів був всюди

2023-04-28 14:10 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +  color: $white;
окей поняв
я не знав цих правил

2023-04-28 14:12 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +$gray: gray;
ну в тебе вже не один тому що в одному випадку ти юзаєш #fff а в іншому текстову назву gray

2023-04-28 14:55 UTC, PetroFedun commented on app/assets/stylesheets/style.scss
> +$gray: gray;
![image](https://user-images.githubusercontent.com/108093441/235181567-2ee3ffe3-f019-4e0e-9b6b-0b6e42595e0e.png)

2023-04-28 14:55 UTC, PetroFedun commented on app/assets/stylesheets/style.scss
> +$gray: gray;
така штука не працює

2023-04-28 14:56 UTC, PetroFedun commented on app/assets/stylesheets/style.scss
> +.form-width {
![image](https://user-images.githubusercontent.com/108093441/235181991-72045ffa-cfcb-4f1e-96e5-12c4637d5ecc.png)

2023-04-28 14:57 UTC, PetroFedun commented on app/assets/stylesheets/style.scss
> +.form-width {
така штука не працює

2023-04-28 18:17 UTC, MishaIlchyshyn commented
@PetroFedun ти зробив реквест на ревю, і паралельно щось робиш
а я в той час дивлюсь твій код
і я подивився, зберіг коменти і тут ти досипаєш новий коміт і мені знов тра дивитись
для того я тобі казав ставити мітку WIP

коли щось робиш став WIP -> зробив -> забрав WIP -> зробив мені реквест на ревю -> я дивлюсь і лишаю коменти або ставлю апрув

2023-04-29 06:50 UTC, PetroFedun commented
@MishaIlchyshyn Мерджити?

2023-04-30 19:19 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +    a {
а шо це за відступ такий?

2023-04-30 19:22 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +      margin: 15px 0;
?

2023-05-01 07:32 UTC, MishaIlchyshyn requested changes

2023-05-01 07:32 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +  max-width:550px;
відступи

2023-05-01 07:32 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +   }
відступ

2023-05-01 07:32 UTC, MishaIlchyshyn commented on app/views/articles/index.html.erb
> +    <li><%= link_to "New Article", new_article_path, class: "btn btn-primary mx-4 mx-xl-3" %></li>
дві однакові кнопки але в них чогось різні стилі

2023-05-01 07:32 UTC, MishaIlchyshyn commented on app/views/articles/show.html.erb
> +  <img src="<%= asset_path('default-article-img.jpg') %>" class="card-img-top mx-auto showing" alt="...">
зроби по аналогії до того як ти зробив в _articles паршалі
тобто зроби один клас **article_img**, опиши там стилі і додай в двох випадках

2023-05-01 07:32 UTC, MishaIlchyshyn commented on app/views/devise/passwords/new.html.erb
> +<main>
main ти вже виніс в application.html.erb

2023-05-01 07:32 UTC, MishaIlchyshyn commented on app/views/devise/registrations/edit.html.erb
> +    <%= f.submit "Update", class:"btn btn-primary" %>
відступ

2023-05-01 07:32 UTC, MishaIlchyshyn commented on app/views/devise/sessions/new.html.erb
> +  <div class="actions mt-3" >
відступ

2023-05-01 07:32 UTC, MishaIlchyshyn commented on app/views/layouts/_header.html.erb
>              <li><%= button_to "Sign out", destroy_user_session_path,data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger btn-dropdown" %></li>
перед data відступ
взагалі якщо є такі довгі строки то переноси на наступну строку

2023-05-01 07:32 UTC, MishaIlchyshyn commented on app/views/static_pages/help.html.erb
> +  That's why we've created this help page to help you if you need it.</p>
```
<p>
  ;lsdjkv;dlsfjmv;sdfmv;dsflmvd;lbml;df
  dls;jkfvds;jmf;d;fjmgvd;slgmvdlos;flm
</p>
<p>
  ;lsdjkv;dlsfjmv;sdfmv;dsflmvd;lbml;df
  dls;jkfvds;jmf;d;fjmgvd;slgmvdlos;flm
</p>
```

2023-05-01 07:34 UTC, MishaIlchyshyn commented
@PetroFedun сам не мерджи

2023-05-01 08:13 UTC, PetroFedun commented on app/assets/stylesheets/style.scss
> +    a {
![image](https://user-images.githubusercontent.com/108093441/235427458-7e6c08aa-74d9-4620-bac0-f2270e473ea1.png)

2023-05-01 08:13 UTC, PetroFedun commented on app/assets/stylesheets/style.scss
> +    a {
так правильно чи як?

2023-05-01 14:32 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +    a {
як на мене то цей відступ вправо не потрібний

2023-05-01 16:42 UTC, MishaIlchyshyn requested changes

2023-05-01 16:42 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +   }
поправ відступ

2023-05-01 16:42 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +    color: $gray;
чим тобі не підходить gray ?
для чого кольори які і так можна записати в іменному вигляді типу white, gray ... виносити в змінну?
що ти таким чином покращуєш?

2023-05-01 16:42 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +  color: $dark_green;
отут є смисл в змінній, тому що без змінної ти не зможеш задати цей колір як dark_green

2023-05-01 16:42 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +
?

2023-05-01 16:42 UTC, MishaIlchyshyn commented on app/assets/stylesheets/style.scss
> +$gray: #808080;
для white і gray не треба змінних

2023-05-01 16:42 UTC, MishaIlchyshyn commented on app/views/static_pages/help.html.erb
> +  </p>
верни свій текст
і зверни увагу на теги p в прикладі який я кинув
я зроби так зі своїм текстом у всіх статік пейджах

2023-05-01 18:37 UTC, MishaIlchyshyn commented on app/views/static_pages/help.html.erb
> +  </p>
ще подивись в statis_pages/about.html.erb

2023-05-01 18:56 UTC, merged